// <auto-generated />
using System;
using Maliev.EmployeeService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.EmployeeService.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260304045055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employee")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_attendance_records");

                    b.ToTable("attendance_records", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<Guid?>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("LogId")
                        .HasName("p_k_audit_logs");

                    b.HasIndex("PrincipalId")
                        .HasDatabaseName("i_x_audit_logs_principal_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("i_x_audit_logs_timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("i_x_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", "employee", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Immutable", "1=1");
                        });
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.BulkJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Errors")
                        .HasColumnType("text")
                        .HasColumnName("errors");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("failed_records");

                    b.Property<Guid>("InitiatedByPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_principal_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("ResultData")
                        .HasColumnType("text")
                        .HasColumnName("result_data");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulRecords")
                        .HasColumnType("integer")
                        .HasColumnName("successful_records");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.HasKey("Id")
                        .HasName("p_k_bulk_jobs");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("i_x_bulk_jobs_completed_at");

                    b.HasIndex("InitiatedByPrincipalId")
                        .HasDatabaseName("i_x_bulk_jobs_initiated_by_principal_id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("i_x_bulk_jobs_job_id");

                    b.HasIndex("JobType")
                        .HasDatabaseName("i_x_bulk_jobs_job_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_bulk_jobs_status");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("i_x_bulk_jobs_status_started_at");

                    b.ToTable("bulk_jobs", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_center");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("DepartmentHeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_head_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("HeadcountLimit")
                        .HasColumnType("integer")
                        .HasColumnName("headcount_limit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_department_id");

                    b.HasKey("Id")
                        .HasName("p_k_departments");

                    b.HasIndex("DepartmentHeadId")
                        .HasDatabaseName("i_x_departments_department_head_id");

                    b.HasIndex("ParentDepartmentId")
                        .HasDatabaseName("i_x_departments_parent_department_id");

                    b.ToTable("departments", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("integer")
                        .HasColumnName("priority_order");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship");

                    b.HasKey("Id")
                        .HasName("p_k_emergency_contacts");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("i_x_emergency_contacts_employee_id");

                    b.HasIndex("EmployeeId", "PriorityOrder")
                        .HasDatabaseName("i_x_emergency_contacts_employee_id_priority_order");

                    b.ToTable("emergency_contacts", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid?>("DottedLineManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dotted_line_manager_id");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_number");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employment_status");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employment_type");

                    b.Property<Guid?>("JobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_application_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("NationalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("national_id");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nationality");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preferred_name");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<DateTime?>("ProbationEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("probation_end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termination_date");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("work_location");

                    b.HasKey("Id")
                        .HasName("p_k_employees");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("i_x_employees_department_id");

                    b.HasIndex("DottedLineManagerId")
                        .HasDatabaseName("i_x_employees_dotted_line_manager_id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_employees_employee_number");

                    b.HasIndex("EmploymentStatus")
                        .HasDatabaseName("i_x_employees_employment_status");

                    b.HasIndex("EmploymentType")
                        .HasDatabaseName("i_x_employees_employment_type");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("i_x_employees_manager_id");

                    b.HasIndex("PrincipalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_employees_principal_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("i_x_employees_start_date");

                    b.HasIndex("TerminationDate")
                        .HasDatabaseName("i_x_employees_termination_date");

                    b.HasIndex("DepartmentId", "EmploymentStatus")
                        .HasDatabaseName("i_x_employees_department_id_employment_status");

                    b.ToTable("employees", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.EmployeeTeamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("p_k_employee_team_assignments");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("i_x_employee_team_assignments_employee_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_employee_team_assignments_team_id");

                    b.ToTable("employee_team_assignments", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.EmploymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id")
                        .HasName("p_k_employment_histories");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("i_x_employment_histories_employee_id");

                    b.ToTable("employment_histories", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.ToTable("incidents", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_positions");

                    b.ToTable("positions", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.SagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_step");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("SagaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saga_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("CorrelationId")
                        .HasName("p_k_saga_states");

                    b.HasIndex("SagaType")
                        .HasDatabaseName("i_x_saga_states_saga_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_saga_states_status");

                    b.ToTable("saga_states", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.SagaStepHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_name");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_type");

                    b.HasKey("Id")
                        .HasName("p_k_saga_step_histories");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("i_x_saga_step_histories_correlation_id");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("i_x_saga_step_histories_executed_at");

                    b.ToTable("saga_step_histories", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_lead_id");

                    b.Property<string>("TeamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_type");

                    b.HasKey("Id")
                        .HasName("p_k_teams");

                    b.HasIndex("TeamLeadId")
                        .HasDatabaseName("i_x_teams_team_lead_id");

                    b.ToTable("teams", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("PreferenceData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preference_data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PrincipalId", "Scope")
                        .HasName("p_k_user_preferences");

                    b.ToTable("user_preferences", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("p_k_work_schedules");

                    b.ToTable("work_schedules", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Sagas.EmployeeTerminationSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<bool>("AccessRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("access_revoked");

                    b.Property<bool>("CompensationArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("compensation_archived");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_state");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("LeaveBalanceClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("leave_balance_closed");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termination_date");

                    b.HasKey("CorrelationId")
                        .HasName("p_k_employee_termination_saga_states");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("i_x_employee_termination_saga_states_current_state");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("i_x_employee_termination_saga_states_employee_id");

                    b.ToTable("employee_termination_saga_states", "employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Department", b =>
                {
                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_departments__employees_department_head_id");

                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_departments_departments_parent_department_id");

                    b.Navigation("DepartmentHead");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.EmergencyContact", b =>
                {
                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "Employee")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_emergency_contacts__employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_employees_departments_department_id");

                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "DottedLineManager")
                        .WithMany("DottedLineReports")
                        .HasForeignKey("DottedLineManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_employees_employees_dotted_line_manager_id");

                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_employees_employees_manager_id");

                    b.OwnsOne("Maliev.EmployeeService.Domain.ValueObjects.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("MobilePhone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("mobile_phone");

                            b1.Property<string>("PersonalEmail")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("personal_email");

                            b1.Property<string>("WorkEmail")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("work_email");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees", "employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("Maliev.EmployeeService.Domain.ValueObjects.LegalName", "LegalName", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("middle_name");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees", "employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DottedLineManager");

                    b.Navigation("LegalName")
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.EmployeeTeamAssignment", b =>
                {
                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "Employee")
                        .WithMany("TeamAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_employee_team_assignments_employees_employee_id");

                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_employee_team_assignments__teams_team_id");

                    b.Navigation("Employee");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.EmploymentHistory", b =>
                {
                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_employment_histories_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Team", b =>
                {
                    b.HasOne("Maliev.EmployeeService.Domain.Entities.Employee", "TeamLead")
                        .WithMany()
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_teams_employees_team_lead_id");

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("DottedLineReports");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("TeamAssignments");
                });

            modelBuilder.Entity("Maliev.EmployeeService.Domain.Entities.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
